CREATE DATABASE IF NOT EXISTS `book_lending_platform` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `book_lending_platform`;

CREATE TABLE IF NOT EXISTS `user` (
  `name_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(100) NOT NULL COMMENT '密码（加密后存储）',
  `real_name` VARCHAR(50) NOT NULL COMMENT '真实姓名',
  `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
  `phone` VARCHAR(20) NOT NULL COMMENT '手机号',
  `identity_card` VARCHAR(20) NOT NULL COMMENT '身份证号',
  `major` VARCHAR(50) DEFAULT NULL COMMENT '专业',
  `user_type` TINYINT NOT NULL COMMENT '用户类型：1用户，2图书管理员，3系统管理员',
  `max_borrow_count` INT DEFAULT 5 COMMENT '最大借阅数量',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0禁用，1正常',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`name_id`),
  UNIQUE KEY `uk_user_username` (`username`),
  UNIQUE KEY `uk_user_email` (`email`),
  UNIQUE KEY `uk_user_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `book` (
  `book_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '图书ID',
  `isbn` VARCHAR(20) NOT NULL COMMENT 'ISBN号',
  `book_name` VARCHAR(200) NOT NULL COMMENT '书名',
  `author` VARCHAR(100) NOT NULL COMMENT '作者',
  `publisher` VARCHAR(100) NOT NULL COMMENT '出版社',
  `publish_date` DATE DEFAULT NULL COMMENT '出版日期',
  `category_id` BIGINT DEFAULT NULL COMMENT '分类ID',
  `sub_field` VARCHAR(50) DEFAULT NULL COMMENT '计算机子领域',
  `difficulty_level` TINYINT NOT NULL COMMENT '难度等级：1入门，2进阶，3专家',
  `suitable_scene` VARCHAR(100) DEFAULT NULL COMMENT '适用场景',
  `cover_url` VARCHAR(200) DEFAULT NULL COMMENT '封面图片URL',
  `description` TEXT COMMENT '图书简介',
  `catalog` TEXT COMMENT '目录',
  `author_intro` TEXT COMMENT '作者简介',
  `target_audience` VARCHAR(200) DEFAULT NULL COMMENT '适用人群',
  `total_count` INT DEFAULT 0 COMMENT '馆藏总数',
  `available_count` INT DEFAULT 0 COMMENT '可借数量',
  `borrow_count` INT DEFAULT 0 COMMENT '借阅次数',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0下架，1上架',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`book_id`),
  UNIQUE KEY `uk_book_isbn` (`isbn`),
  KEY `idx_book_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='图书表';

-- 初始化图书数据（仅用于空库初始化，重复执行可能因 ISBN 唯一键报错）
INSERT INTO `book` (
  `isbn`,
  `book_name`,
  `author`,
  `publisher`,
  `publish_date`,
  `sub_field`,
  `difficulty_level`,
  `suitable_scene`,
  `cover_url`,
  `description`,
  `target_audience`,
  `total_count`,
  `available_count`,
  `borrow_count`,
  `status`
) VALUES
  (
    '9787111128069',
    '深入理解计算机系统（第3版）',
    'Randal E. Bryant / David R. O’Hallaron',
    '机械工业出版社',
    '2016-04-01',
    '系统',
    3,
    '课程学习, 面试提升',
    'https://images.unsplash.com/photo-1508169351866-777fc0047ac5?auto=format&fit=crop&w=480&q=80',
    '经典系统教材，覆盖程序表示、处理器体系结构、存储层次与并发。',
    '计算机相关专业学生, 系统开发者',
    12,
    9,
    628,
    1
  ),
  (
    '9787111213826',
    '代码大全（第2版）',
    'Steve McConnell',
    '电子工业出版社',
    '2006-06-01',
    '软件工程',
    2,
    '工程实践, 代码质量',
    'https://images.unsplash.com/photo-1503543791519-1694c6b20779?auto=format&fit=crop&w=480&q=80',
    '全面的软件构建指南，涵盖编码规范、设计与调试实践。',
    '有一定编码经验的开发者',
    8,
    3,
    412,
    1
  ),
  (
    '9787115474063',
    '图解 HTTP',
    '上野宣',
    '人民邮电出版社',
    '2014-05-01',
    '网络',
    1,
    '入门学习',
    'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=480&q=80',
    '用插图解释 HTTP/HTTPS、Cookies、缓存与安全机制。',
    '网络与 Web 开发入门者',
    15,
    12,
    355,
    1
  ),
  (
    '9787111629245',
    'Java 核心技术 卷 I（第11版）',
    'Cay S. Horstmann',
    '机械工业出版社',
    '2020-01-01',
    'Java',
    2,
    '课程学习, 日常开发',
    'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=480&q=80',
    '面向 Java SE 的核心概念与 API 实战。',
    'Java 开发者, 计算机相关专业学生',
    10,
    6,
    271,
    1
  ),
  (
    '9787115428028',
    'Spring 实战（第5版）',
    'Craig Walls',
    '人民邮电出版社',
    '2019-03-01',
    'Java',
    2,
    'Web 开发, 后端实战',
    'https://images.unsplash.com/photo-1527135472885-9908bbe7d61f?auto=format&fit=crop&w=480&q=80',
    '以项目驱动讲解 Spring 生态核心能力。',
    '后端开发者',
    9,
    5,
    189,
    1
  ),
  (
    '9787111636649',
    'MySQL 必知必会',
    'Ben Forta',
    '人民邮电出版社',
    '2019-08-01',
    '数据库',
    1,
    'SQL 入门',
    'https://images.unsplash.com/photo-1601221018729-15aec0cf430f?auto=format&fit=crop&w=480&q=80',
    '从 SELECT 到 JOIN 与子查询，快速掌握 SQL 基础。',
    '数据库入门者, 后端开发者',
    18,
    14,
    306,
    1
  ),
  (
    '9787111558422',
    '高性能 MySQL（第3版）',
    'Baron Schwartz / Peter Zaitsev / Vadim Tkachenko',
    '电子工业出版社',
    '2017-09-01',
    '数据库',
    3,
    '性能优化, 生产排障',
    'https://images.unsplash.com/photo-1651261525945-5382b021bfeb?auto=format&fit=crop&w=480&q=80',
    '深入 MySQL 内部与性能优化方法。',
    '中高级后端开发者, DBA',
    6,
    2,
    147,
    1
  ),
  (
    '9787111126942',
    '算法（第4版）',
    'Robert Sedgewick / Kevin Wayne',
    '人民邮电出版社',
    '2012-10-01',
    '算法',
    2,
    '课程学习, 面试准备',
    'https://images.unsplash.com/photo-1689023542260-faa90df36bb4?auto=format&fit=crop&w=480&q=80',
    '经典算法与数据结构教材，配套大量示例与练习。',
    '计算机相关专业学生, 面试准备者',
    11,
    8,
    498,
    1
  ),
  (
    '9787111652038',
    '设计数据密集型应用',
    'Martin Kleppmann',
    '中国电力出版社',
    '2018-11-01',
    '分布式',
    3,
    '架构设计, 系统演进',
    'https://images.unsplash.com/photo-1732304720450-0fe31c39f491?auto=format&fit=crop&w=480&q=80',
    '从存储、复制、分区到流处理，系统性讲解数据系统设计。',
    '架构师, 中高级后端开发者',
    7,
    4,
    233,
    1
  ),
  (
    '9787111605904',
    'Python 机器学习基础教程',
    'Sebastian Raschka / Vahid Mirjalili',
    '人民邮电出版社',
    '2019-01-01',
    '机器学习',
    2,
    '课程学习, 项目实践',
    'https://images.unsplash.com/photo-1570047435693-4a1d6bbc6220?auto=format&fit=crop&w=480&q=80',
    '结合 scikit-learn 的端到端机器学习入门与实践。',
    '数据分析入门者, 开发者',
    9,
    7,
    198,
    1
  );

CREATE TABLE IF NOT EXISTS `book_category` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `category_name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `parent_id` BIGINT DEFAULT 0 COMMENT '父分类ID',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0禁用，1启用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`category_id`),
  KEY `idx_book_category_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='图书分类表';

CREATE TABLE IF NOT EXISTS `borrow_record` (
  `borrow_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `book_id` BIGINT NOT NULL COMMENT '图书ID',
  `borrow_date` DATETIME NOT NULL COMMENT '借阅日期',
  `due_date` DATETIME NOT NULL COMMENT '应还日期',
  `return_date` DATETIME DEFAULT NULL COMMENT '实际归还日期',
  `renew_count` INT DEFAULT 0 COMMENT '续借次数',
  `status` TINYINT NOT NULL COMMENT '状态：1借阅中，2已归还，3超期',
  `overdue_days` INT DEFAULT 0 COMMENT '超期天数',
  `fine_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '罚款金额',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`borrow_id`),
  KEY `idx_borrow_record_user_id` (`user_id`),
  KEY `idx_borrow_record_book_id` (`book_id`),
  CONSTRAINT `fk_borrow_record_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`),
  CONSTRAINT `fk_borrow_record_book_id` FOREIGN KEY (`book_id`) REFERENCES `book` (`book_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='借阅记录表';

CREATE TABLE IF NOT EXISTS `reservation_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `book_id` BIGINT NOT NULL COMMENT '图书ID',
  `reservation_date` DATETIME NOT NULL COMMENT '预约日期',
  `expire_date` DATETIME NOT NULL COMMENT '预约失效日期',
  `status` TINYINT NOT NULL COMMENT '状态：1预约中，2已借阅，3已取消，4已过期',
  `queue_position` INT DEFAULT NULL COMMENT '队列位置',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_reservation_record_user_id` (`user_id`),
  KEY `idx_reservation_record_book_id` (`book_id`),
  CONSTRAINT `fk_reservation_record_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`),
  CONSTRAINT `fk_reservation_record_book_id` FOREIGN KEY (`book_id`) REFERENCES `book` (`book_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='预约记录表';

CREATE TABLE IF NOT EXISTS `collection_category` (
  `collection_category_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '收藏分类ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `category_name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `is_default` TINYINT DEFAULT 0 COMMENT '是否默认分类：0否，1是',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0禁用，1启用',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`collection_category_id`),
  UNIQUE KEY `uk_collection_category_user_name` (`user_id`, `category_name`),
  UNIQUE KEY `uk_collection_category_id_user_id` (`collection_category_id`, `user_id`),
  CONSTRAINT `fk_collection_category_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户收藏分类表';

CREATE TABLE IF NOT EXISTS `collection_record` (
  `collection_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `book_id` BIGINT NOT NULL COMMENT '图书ID',
  `collection_category_id` BIGINT DEFAULT NULL COMMENT '收藏分类ID',
  `collection_date` DATETIME NOT NULL COMMENT '收藏日期',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`collection_id`),
  UNIQUE KEY `uk_collection_record_user_book` (`user_id`, `book_id`),
  KEY `idx_collection_record_book_id` (`book_id`),
  KEY `idx_collection_record_category_user_id` (`collection_category_id`, `user_id`),
  CONSTRAINT `fk_collection_record_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`),
  CONSTRAINT `fk_collection_record_book_id` FOREIGN KEY (`book_id`) REFERENCES `book` (`book_id`),
  CONSTRAINT `fk_collection_record_category_user_id` FOREIGN KEY (`collection_category_id`, `user_id`) REFERENCES `collection_category` (`collection_category_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收藏记录表';

CREATE TABLE IF NOT EXISTS `user_preference` (
  `preference_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `prefer_fields` VARCHAR(200) DEFAULT NULL COMMENT '偏好领域，多个用逗号分隔',
  `prefer_difficulty` TINYINT DEFAULT NULL COMMENT '偏好难度',
  `prefer_scenes` VARCHAR(200) DEFAULT NULL COMMENT '偏好场景',
  `recommend_new_book` TINYINT DEFAULT 0 COMMENT '优先推荐新书：0否，1是',
  `recommend_hot_book` TINYINT DEFAULT 0 COMMENT '优先推荐热门书：0否，1是',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`preference_id`),
  UNIQUE KEY `uk_user_preference_user_id` (`user_id`),
  CONSTRAINT `fk_user_preference_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户偏好表';

CREATE TABLE IF NOT EXISTS `book_location` (
  `location_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '位置ID',
  `book_id` BIGINT NOT NULL COMMENT '图书ID',
  `floor` INT NOT NULL COMMENT '楼层',
  `area` VARCHAR(20) NOT NULL COMMENT '区域',
  `shelf_no` VARCHAR(20) NOT NULL COMMENT '书架号',
  `layer` INT NOT NULL COMMENT '层数',
  `rfid_code` VARCHAR(50) DEFAULT NULL COMMENT 'RFID标签码',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`location_id`),
  UNIQUE KEY `uk_book_location_rfid_code` (`rfid_code`),
  KEY `idx_book_location_book_id` (`book_id`),
  CONSTRAINT `fk_book_location_book_id` FOREIGN KEY (`book_id`) REFERENCES `book` (`book_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='图书位置表';

CREATE TABLE IF NOT EXISTS `comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `user_id` BIGINT NOT NULL COMMENT '发表评论的用户ID',
  `book_id` BIGINT NOT NULL COMMENT '被评论的图书ID',
  `content` TEXT NOT NULL COMMENT '评论正文',
  `rating` TINYINT NOT NULL COMMENT '评分，1-5分',
  `like_count` INT DEFAULT 0 COMMENT '点赞数量',
  `status` TINYINT DEFAULT 1 COMMENT '状态：0隐藏，1显示，2审核中',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_comment_user_id` (`user_id`),
  KEY `idx_comment_book_id` (`book_id`),
  CONSTRAINT `fk_comment_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`name_id`),
  CONSTRAINT `fk_comment_book_id` FOREIGN KEY (`book_id`) REFERENCES `book` (`book_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='评论表';
